---

- name: change files on remote hosts
  hosts: webservers
  become: yes
  vars_files:
   - /home/vish/ansible/variables/credentials.yml

  tasks:
   - name: Copy index.html to web root
     copy:
       src: index.html
       dest: /usr/share/nginx/html/index.html
       owner: root
       group: root
       mode: '0644'
       backup: yes
   - name: Update hosts file on remote host
     blockinfile:
      path: /etc/hosts
      backup: yes
      marker: "# {mark} ANSIBLE MANAGED BLOCK "
      insertbefore: '^###End'
      block: |
        192.168.1.1 bbrouter
        192.168.1.204 homepc
