---
- name: create new user 
  hosts: webservers
  become: yes
  tasks:
  - name: create new user
    user:
     name: test
     password: test123
     state: present
  - name: install nginx
    yum:
     name: nginx
     state: present
     update_cache: yes
     name: links
     state: present
     update_cache: yes
